### ISSUE TITLE
[BUG] Symbols package publishing failed

### ISSUE THREAD

**Issue by nicksterx** [sandialabs/Gulliver#41]
# Describe the bug

Symbols package publishing failed. The uploaded symbols package contains one or more pdbs that are not portable.

# Expected behavior

Should publish portable pdb's for snupkg

# Example of how to Reproduce

1. Create build
1. Release build from Azure Release Pipeline
1. See Nuget.org report the error
![image](https://user-images.githubusercontent.com/440031/68609822-95d90780-0473-11ea-8486-c49deeca79be.png)

# Code Information

Affects Version 1.0.2

# Proposed solutions

Add Arguments to pipeline task DotNetCoreCLI@2 
```yml
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    arguments: '--include-symbols -p:SymbolPackageFormat=snupkg'
    packagesToPack: '**/Arcus.csproj;'
```
# Can you help?

I am going to create a pull request for this.
